const Data = [
    {
        id: "1",
        title: "Thermodynamics book",
        category: "College Book",
        user: "John Doe",
        img: "https://zamroo.s3.ap-south-1.amazonaws.com/images/product-images/books-magazines/books/medium/20200130061413-26952.png",
        desc: "A book of Thermodynamics by P K Nag.",
    },
    {
        id: "2",
        title: "Calculus book",
        category: "College Book",
        user: "Lee Nonmi",
        img: "https://qph.cf2.quoracdn.net/main-qimg-7994ee6ba77511ed9c1fa1999a6ec841.webp",
        desc: "A book of Calculus.",
    },
    {
        id: "3",
        title: "OS Book",
        category: "College Book",
        user: "C. Yasoon",
        img: "https://www.clankart.com/user_uploads/Operating_System_Concepts15134159431.jpg",
        desc: "A book of Operating System concepts.",
    },
    {
        id: "4",
        title: "COA Book",
        category: "College Book",
        user: "Ray Sin",
        img: "https://rukminim1.flixcart.com/image/416/416/kjiwfbk0-0/book/p/q/c/computer-organization-and-architecture-original-imafz2ym3buqergz.jpeg?q=70",
        desc: "A book of Computer Organization and Architecture.",
    },
    {
        id: "5",
        title: "Semi-conductor Devices Book",
        category: "College Book",
        user: "John Quil",
        img: "https://www.wileyindia.com/pub/media/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/9/7/9788126556755.jpg",
        desc: "A book of Semi-conductor Devices.",
    },
    {
        id: "6",
        title: "Dorm Table",
        category: "Table",
        user: "John Doe",
        img: "https://college.harvard.edu/sites/default/files/styles/max_800_x_985/public/images/p_20151125_231323.jpg?itok=CitsTXfh",
        desc: "A Table for college dorm.",
    },
    {
        id: "7",
        title: "Night lamp",
        category: "Other Items",
        user: "Allie Grater",
        img: "https://rukminim2.flixcart.com/image/416/416/ksoz53k0/emergency-light/k/l/0/chargeable-desk-lamp-with-organiser-phone-holder-night-light-pin-original-imag67d2f4kskmqt.jpeg?q=70",
        desc: "A night lamp",
    },
    {
        id: "8",
        title: "Table lamp",
        category: "Other Items",
        user: "Peg Legge",
        img: "https://i.pinimg.com/564x/eb/08/cb/eb08cbd80ecbc23924e60947caf22359.jpg",
        desc: "A table lamp.",
    },
    {
        id: "9",
        title: "College Dorm Bed",
        category: "Furniture",
        user: "John Doe",
        img: "https://guide-images.cdn.ifixit.com/igi/rouAR16Lacf5ECdQ.medium",
        desc: "A used Collage Dorm bed.",
    },
    {
        id: "10",
        title: "Matress",
        category: "Other Items",
        user: "Teri Dactyl",
        img: "https://3989ac5bcbe1edfc864a-0a7f10f87519dba22d2dbc6233a731e5.ssl.cf2.rackcdn.com/Martinmattress/Dorm_Mattress_Flat_1200_x1200/Dorm_Mattress_Flat_1200_x1200_310x310.jpg",
        desc: "A dorm matress.",
    },
];

export default Data;
